defaults: &defaults
  app_name: "MIS"
  auth_host: "http://staging.open.icar99.com"
  countdown_warnning_interval: 2

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  auth_host: "http://open.icar99.cn"

staging:
  <<: *defaults
  auth_host: "http://staging.open.icar99.com"
