defaults: &defaults
  app_name: "MIS"
  auth_host: "http://localhost:3002"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults
  auth_host: "http://staging.open.icar99.com"
