default: &default
  adapter: postgresql
  encoding: utf8
  pool: 50
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: store_development
  username: issac
  password: issac

test:
  <<: *default
  database: store_test
  username: issac
  password: issac
