works:
  -
    name: pos管理
    code: pos
    sub_categories:
      -
        name: 收银
        url: /pos/cashier/checkouts
        idx: 1
      -
        name: 业务开单
        url: /pos/store_orders/new
        idx: 2
  -
    name: 现场管理
    code: xianchang
    sub_categories:
      -
        name: 施工现场
        url: /xianchang/store_workstations
        idx: 3
      -
        name: 人员调度
        url: /xianchang/groups
        idx: 4
  -
    name: 销售管理
    code: xiaoshou
    sub_categories:
      -
        name: 商品
        url: /mkis/materials
        idx: 5
      -
        name: 服务
        url: /xiaoshou/main#store_services
        idx: 6
      -
        name: 套餐
        url: /xiaoshou/main#store_packages
        idx: 7
  -
    name: 库存管理
    code: kucun
    sub_categories:
      -
        name: 商品目录
        url: /kucun
        idx: 8
      -
        name: 入库
        url: /kucun/material_inventories/new
        idx: 9
      -
        name: 出库
        url: /kucun/outings/new
        idx: 10
      -
        name: 采购
        url: /srm/material_orders/nowaus
        idx: 11
      -
        name: 临时订货
        url: /kucun/temporary_material_orders
        idx: 12
      -
        name: 盘点
        url: /kucun/physical_inventories/new
        idx: 13
      -
        name: 报损
        url: /kucun/shrinkages/new
        idx: 14
      -
        name: 退货
        url: /kucun/returnings/new
        idx: 15
  -
    name: 客户管理
    code: crm
    sub_categories:
      -
        name: 客户列表
        url: /xiaoshou/main#store_customers
        idx: 16
  -
    name: 供应商管理
    code: srm
    sub_categories:
      -
        name: 供应商列表
        url: /srm/store_suppliers
        idx: 17
