json.(
  @setting.workflow,
  :engineer_count,
  :engineer_count_enable,
  :engineer_level_enable,
  :engineer_level,
  :standard_time,
  :standard_time_enable,
  :buffering_time,
  :buffering_time_enable,
  :factor_time,
  :nominated_workstation,
  :mechanic_commission_template_id,
  :position_mode,
  :workstation_ids
)
